[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
axum = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
opensearch = { workspace = true }
url = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
aws-sdk-sqs = { workspace = true }

[dev-dependencies]
tower = { workspace = true }
uuid = { workspace = true }
reqwest = { version = "0.12", features = ["json"] }
aws-config = { workspace = true }
