[package]
name = "delete-cleanup"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
axum = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-sdk-sqs = { workspace = true }
aws-sdk-cloudwatch = { workspace = true }
aws-sdk-cloudfront = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
tower = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
